# Generated by Django 5.1.5 on 2025-01-28 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50000, null=True)),
                ('role', models.CharField(blank=True, max_length=50000, null=True)),
                ('BattingInnings', models.CharField(blank=True, max_length=50000, null=True)),
                ('BattingRuns', models.CharField(blank=True, max_length=50000, null=True)),
                ('BattingAverage', models.CharField(blank=True, max_length=50000, null=True)),
                ('BattingStrikeRate', models.CharField(blank=True, max_length=50000, null=True)),
                ('Balls', models.CharField(blank=True, max_length=50000, null=True)),
                ('BowlingWickets', models.CharField(blank=True, max_length=50000, null=True)),
                ('BowlingAverage', models.CharField(blank=True, max_length=50000, null=True)),
                ('BowlingEconomy', models.CharField(blank=True, max_length=50000, null=True)),
                ('BowlingStrikeRate', models.CharField(blank=True, max_length=50000, null=True)),
                ('Stumping', models.CharField(blank=True, max_length=50000, null=True)),
                ('basePrice', models.CharField(blank=True, max_length=50000, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('amt', models.CharField(blank=True, max_length=50000, null=True)),
                ('assignedTo', models.CharField(blank=True, max_length=50000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('accessGroup', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(max_length=500, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=2550, null=True)),
                ('player_id', models.CharField(blank=True, max_length=2550, null=True)),
                ('teamname', models.CharField(blank=True, max_length=2550, null=True)),
                ('lock_timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='activePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('activePlayer_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.player')),
            ],
        ),
    ]
