# Generated by Django 5.1.5 on 2025-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbid',
            name='user',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
