# Generated by Django 5.1.5 on 2025-01-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college',
        ),
        migrations.AddField(
            model_name='user',
            name='userbudget',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
