# Generated by Django 5.1.5 on 2025-01-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_college_user_userbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
