# Generated by Django 5.1.5 on 2025-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='BallsFaced',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='BattingType',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='BowlingType1',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='BowlingType2',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='NoDismissal',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='RunsConceded',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
